### ISSUE TITLE
Discussions?

### ISSUE THREAD

**Issue by jpadfield** [E-RIHS/schema#1]
Do we want to enable discussions in this repo to explore ideas about the schema and keep issues for specific actions?

**Comment by kobbejager** [comment]
I would argue to use github's issues feature in this repo only to have an overview of and keep track of tasks specific for the schema. I would avoid using it as a discussion forum, in order not to create yet another channel besides the Wednesday meetings, zulip and teams. Or in other words: we add issues as a result of the discussions on zoom/teams/zulip as reminders of what was agreed to be done.

By the way, Sophia is not watching this repo at this moment, and will not get notified.

**Comment by jpadfield** [comment]
ok
