### ISSUE TITLE
enums in person and organisation

### ISSUE THREAD

**Issue by kobbejager** [E-RIHS/schema#10]
The person and organisations schemas have the following enums:
- title (person: Mr, Ms...)
- pid types for external pids (person: orcid..., organisation: ror...)

These are currently hard coded enums. Should they be pulled from a controlled list in the vocabulary server?

**Comment by jpadfield** [comment]
How extensive do we need these lists to be?

**Comment by jpadfield** [comment]
Titles could be based on some of those listed at: https://en.wikipedia.org/wiki/English_honorifics

**Comment by jpadfield** [comment]
Some updates required - adding the following and these two list will be done:

arXiv
bibcode
EAN13
EISSN
IGSN
ISTC
LISSN
PMID
UPC
Crossref Funder ID
ISNI
ISTC
LSID
Other PID

**Comment by jpadfield** [comment]
All done
