### ISSUE TITLE
Technique schema issues

### ISSUE THREAD

**Issue by kobbejager** [E-RIHS/schema#15]
- [x] **e-rihs_vocab_url**: a list of pids to the vocabulary URL. This should probably be a controlled list
- [x] **preferred_label**: while I do understand the reason to have this in the schema, do we expect the service providers to copy the preferred name from the vocab to here? Or should we hide script it to fetch the preferred label based on the above vocab url? To complicate things more: this is a simple field, while e-rihs_vocab_url is an array.
- [x] **measurable_properties > measurable_property > property**: is currently an example list with values "composition, width, thickness, colour, roughness, lifespan". Needs to be a controlled list?
- [x] **measurable_properties > measurable_property > material_category** is an array of strings that are currently an example list with values "wood, stone, glass, ceramic, canvas, paint". Needs to be a controlled list?

**Comment by jpadfield** [comment]
measurable_properties > measurable_property > property need to extend the list.

Chemical Composition
Physical Properties 
Mechanical properties
Age
Condition state

**Comment by jpadfield** [comment]
Structural Properties
Chemical Composition
Chemical Properties
Physical Properties
Mechanical properties
Age
Condition state

**Comment by sophiasot** [comment]
Here is our discussion of last week for the short measurable property list, and here below some examples for each,
Physical properties
	Examples: colour, roughness, texture, gloss, transparency, mass, weight, porosity, permeability, density, physical dimensions, distance, 
Structural properties
       Examples: material configuration, layer stratigraphy, layer thickness, geometric characteristics, grain size, 
Mechanical properties
	Examples: strength, hardness, toughnes, elasticity, structural resilience, mechanical behaviour, 
Chemical properties
	Examples: alkalinity, acidity, hygroscopicity, 
Chemical composition 
	Examples: Elemental composition, molecular composition, crystal structure, mineral composition, constituent materials, 
Condition state
       Examples: colour change (discolouration, fading), drying, brittleness, cracking/ crack pattern, delamination, degradation, dissociation, corrosion, oxidation, soiling
Age	
	Examples: lifetime, age, 
Environmental parameters
	Examples: Temperature, RH, Light, Pollutants

**Comment by jpadfield** [comment]
Ok, I have now added in a Material Properties list based on these terms - I have added in very rough AI generated definitions but I have not linked any of these to defined terms in AAT or Wikidata etc. This can be done as an additional step
