### ISSUE TITLE
More robust  "prepended" controlled lists

### ISSUE THREAD

**Issue by kobbejager** [E-RIHS/schema#23]
In some of the controlled lists we are prepending terms like `other` and `not applicable`. At the moment, this is done when building the controlled list schema in Cordra. This is defined and controlled as follows:

```json
"material": {
    "title": "Material",
    "type": "string",
    "e-rihs": {
        "enum_source": "http://hdl.handle.net/21.11158/0002-8925-0082-c469",
        "enum_prepend": [
            {
                "label": "(other)",
                "term": "https://hdl.handle.net/21.11158/0001-m4lp36rj04l0f9268bc0c2v6g"
            }
        ]
    }
}
```

This creates confusion, since the ecls endpoints do not have these additional terms, while cordra has. Other UIs would have to implement similar workarounds. There is a risk that different UIs handle this differently.

I propose that we add the special terms directly to the groups in Opentheso. To force them on top of the alphabetically ordered lists, we could name those terms in brackets: e.g. `(other)`. This is a clean solution, which clearly differentiates them from the normal terms in the list, and probably doesn't require any additional code or workarounds in ecls and cordra.

Does this seem ok?

**Comment by jpadfield** [comment]
I have mixed feelings about the brackets, but happy to go with the consensus.

**Comment by kobbejager** [comment]
I agree it is not ideal. A dropdown with sections would probably be better, but this is not possible with json-editor or cordra, and will even be hackerish to implement in bespoke components.

My thought was that having those special terms directly into the Opentheso groups would be the cleanest and safest way to guarantee that every single application using this group in some form, would use the full group including those special terms. And the least amount of code required, the least risks on breaking things. I guess that prepending them in ecls (as was the case in cordra) implies that you have to hard-code them in some way, which is less sustainable when we add more of those special terms. And finally, a preferred label is just a label which can be changed afterwards. Anyway, I'm also happy to go with the consensus, but there are only two technical people here ;-)

**Comment by jpadfield** [comment]
Ok, this works now, see: https://research.ng-london.org.uk/ecls/?group=g49&simple&refresh

I have created a special group: g50: https://research.ng-london.org.uk/ecls/?group=g50&simple&refresh

If any list pulled from the system contains any of the terms in this special list then they will get pushed to the top of the list. So we can change the labels in this group as needed in Opentheso refresh the lists and it should still work.

We just need to agree which list should have "other" or "non applicable" in it.

**Comment by jpadfield** [comment]
These are all done now
