### ISSUE TITLE
Controlled list for "reference type"

### ISSUE THREAD

**Issue by kobbejager** [E-RIHS/schema#6]
https://github.com/E-RIHS/schema/blob/c90a8a677061b9371c97aa2bd2cadad72fb82c76/service-v1.0.schema.json#L364C21-L373C22

**Comment by jpadfield** [comment]
I have called it a reference "role" rather than a "type" in the vocab system, but it is there now as: https://research.ng-london.org.uk/ecls/?group=g19

**Comment by kobbejager** [comment]
fixed
